Repository rtrclubiitj/rtrclubiitj.github.io, pull requests merged in 2019-09, with the labels that each got.

#31 Modified Text Area Size
  assets/css/main.scss
Labels: bug, enhancement

#34 Added blog for Ganesh Chaturthi
  _posts/2019-08-26-post_14.md
  _posts/2019-08-29-post_15.md
  _posts/2019-09-02-post_16.md
  images/post_16.jpg
Labels: blog

#39 Added installation cermony blog
  _posts/2019-09-20-mom_3.md
  _posts/2019-09-28-post_17.md
  images/post_17.png
Labels: blog, minutes-of-meetings
