Repository rtrclubiitj/rtrclubiitj.github.io, pull requests merged in 2019-08, with the labels that each got.

#2 Post 5
  _posts/2018-08-28-post_4.md
  _posts/2018-09-05-post_3.md
  _posts/2018-09-23-post_2.md
  _posts/2018-11-08-post_1.md
  _posts/2019-08-11-post_5.md
  assets/images/post_5.jpeg
Labels: blog

#6 Added blog entry for Eid and Shrawan
  _posts/2019-08-12-post_6.md
  assets/images/post_6.jpg
Labels: blog

#10 Added blog entry for Indpendence Day
  _posts/2019-08-15-post_7.md
  images/post_7.jpg
Labels: blog

#14 Modified gitignore to untrack sass-cache
  .gitignore
  .sass-cache/09f45e02529ee1573933e106f3eccde0ccacb33a/_box.scssc
  .sass-cache/09f45e02529ee1573933e106f3eccde0ccacb33a/_button.scssc
  .sass-cache/09f45e02529ee1573933e106f3eccde0ccacb33a/_form.scssc
  .sass-cache/09f45e02529ee1573933e106f3eccde0ccacb33a/_icon.scssc
  .sass-cache/09f45e02529ee1573933e106f3eccde0ccacb33a/_image.scssc
  .sass-cache/09f45e02529ee1573933e106f3eccde0ccacb33a/_list.scssc
  .sass-cache/09f45e02529ee1573933e106f3eccde0ccacb33a/_pagination.scssc
  .sass-cache/09f45e02529ee1573933e106f3eccde0ccacb33a/_section.scssc
  .sass-cache/09f45e02529ee1573933e106f3eccde0ccacb33a/_table.scssc
  .sass-cache/5f27935b05e51886eafe9d08be83b3fe30455e8b/_functions.scssc
  .sass-cache/5f27935b05e51886eafe9d08be83b3fe30455e8b/_mixins.scssc
  .sass-cache/5f27935b05e51886eafe9d08be83b3fe30455e8b/_skel.scssc
  .sass-cache/5f27935b05e51886eafe9d08be83b3fe30455e8b/_vars.scssc
  .sass-cache/c5b7c3c417d3f06303e74130bb149f9975c47efc/_page.scssc
  .sass-cache/c5b7c3c417d3f06303e74130bb149f9975c47efc/_typography.scssc
  .sass-cache/f961d11b4f4ad626003142f184aa2c1ea8f28766/_footer.scssc
  .sass-cache/f961d11b4f4ad626003142f184aa2c1ea8f28766/_header.scssc
  .sass-cache/f961d11b4f4ad626003142f184aa2c1ea8f28766/_intro.scssc
  .sass-cache/f961d11b4f4ad626003142f184aa2c1ea8f28766/_main.scssc
  .sass-cache/f961d11b4f4ad626003142f184aa2c1ea8f28766/_nav.scssc
  .sass-cache/f961d11b4f4ad626003142f184aa2c1ea8f28766/_navPanel.scssc
  .sass-cache/f961d11b4f4ad626003142f184aa2c1ea8f28766/_wrapper.scssc
  Gemfile.lock
Labels: workflow

#15 Removed sass-cache completely
  .gitignore
Labels: bug, workflow

#13 Added twitter icon
  .sass-cache/179486f0edcdd89e20932b6cfffd5e067785e80d/_box.scssc
  .sass-cache/179486f0edcdd89e20932b6cfffd5e067785e80d/_button.scssc
  .sass-cache/179486f0edcdd89e20932b6cfffd5e067785e80d/_form.scssc
  .sass-cache/179486f0edcdd89e20932b6cfffd5e067785e80d/_icon.scssc
  .sass-cache/179486f0edcdd89e20932b6cfffd5e067785e80d/_image.scssc
  .sass-cache/179486f0edcdd89e20932b6cfffd5e067785e80d/_list.scssc
  .sass-cache/179486f0edcdd89e20932b6cfffd5e067785e80d/_pagination.scssc
  .sass-cache/179486f0edcdd89e20932b6cfffd5e067785e80d/_section.scssc
  .sass-cache/179486f0edcdd89e20932b6cfffd5e067785e80d/_table.scssc
  .sass-cache/5137850c87cd5336ab699f620eccd23f516e4dbc/_page.scssc
  .sass-cache/5137850c87cd5336ab699f620eccd23f516e4dbc/_typography.scssc
  .sass-cache/8b9eed03a9c452611cc3811e40b7843f253eff8b/_footer.scssc
  .sass-cache/8b9eed03a9c452611cc3811e40b7843f253eff8b/_header.scssc
  .sass-cache/8b9eed03a9c452611cc3811e40b7843f253eff8b/_intro.scssc
  .sass-cache/8b9eed03a9c452611cc3811e40b7843f253eff8b/_main.scssc
  .sass-cache/8b9eed03a9c452611cc3811e40b7843f253eff8b/_nav.scssc
  .sass-cache/8b9eed03a9c452611cc3811e40b7843f253eff8b/_navPanel.scssc
  .sass-cache/8b9eed03a9c452611cc3811e40b7843f253eff8b/_wrapper.scssc
  .sass-cache/e3d8a3bf09e37b6b79be66a9a5068dbd192dc4a3/_functions.scssc
  .sass-cache/e3d8a3bf09e37b6b79be66a9a5068dbd192dc4a3/_mixins.scssc
  .sass-cache/e3d8a3bf09e37b6b79be66a9a5068dbd192dc4a3/_skel.scssc
  .sass-cache/e3d8a3bf09e37b6b79be66a9a5068dbd192dc4a3/_vars.scssc
  _config.yml
  _includes/foot.html
  _includes/nav.html
  assets/css/main.scss
Labels: enhancement, ui

#19 Added blogs for MOM and Humanitarian Day
  _posts/2019-08-12-mom_1.md
  _posts/2019-08-19-post_9.md
Labels: blog, minutes-of-meetings

#20 Added blog for cloth distribution
  _posts/2019-08-12-mom_1.md
  _posts/2019-08-20-post_10.md
  images/post_10.jpg
Labels: blog

#21 Added blog entry
  _posts/2019-08-20-post_11.md
Labels: blog

#22 Added blog for minutes of meetings
  _posts/2019-08-21-mom_2.md
Labels: blog, minutes-of-meetings

#23 Minor fix for MOM
  _posts/2019-08-21-mom_2.md
Labels: blog, minutes-of-meetings

#26 Added blog for UN declared day
  _posts/2019-08-21-post_12.md
Labels: blog

#29 Added blog for Janmashtmi
  _posts/2019-08-24-post_13.md
  images/post_13.jpg
Labels: blog

#30 Added blog for PG interviews
  _posts/2019-08-26-post_14.md
  images/post_14.jpg
Labels: blog

#32 Added blog post
  _posts/2019-08-29-post_15.md
Labels: blog

#33 Added former board details
  _includes/nav.html
  former_boards.md
Labels: club-structure, enhancement
